# Generated by Django 4.2.2 on 2023-06-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_user_remove_status_slug_remove_task_status_task_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
