# Generated by Django 4.2.2 on 2023-06-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_task2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sales.user'),
        ),
    ]
