# Generated by Django 4.2.2 on 2023-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField()),
            ],
        ),
    ]
